"use client";

import { useActionState } from "react";
import { createGiftCardAcceptance, createGiftCardProduct, createProgramme, createProgrammeRate, updateProgramme, updateProgrammeRate, type IntelligenceFormState } from "@/app/admin/(protected)/gift-card-intelligence/actions";
import { Button } from "@/components/ui/button";
import type { IntelligenceProgrammeRow, IntelligenceRateRow } from "@/lib/admin/repos/giftCardIntelligence";

const initialState: IntelligenceFormState = {};
const input = "h-10 w-full rounded-md border bg-background px-3 text-sm";

function Message({ state }: { state: IntelligenceFormState }) {
  if (state.error) return <p role="alert" className="text-sm text-destructive">{state.error}</p>;
  if (state.success) return <p role="status" className="text-sm text-emerald-700">{state.success}</p>;
  return null;
}

export function ProgrammeForm() {
  const [state, action, pending] = useActionState(createProgramme, initialState);
  return <form action={action} className="space-y-3 rounded-lg border p-4"><h2 className="font-semibold">Add reviewed programme</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">ID slug<input name="id" required className={input} placeholder="macquarie-marketplace" /></label><label className="text-sm">Provider<input name="provider" required className={input} /></label><label className="text-sm">Programme name<input name="name" required className={input} /></label><label className="text-sm">Kind<select name="programme_kind" className={input}><option value="bank-account">Bank account</option><option value="membership-catalogue">Membership catalogue</option><option value="employee-benefit">Employee benefit</option></select></label><label className="text-sm sm:col-span-2">Evidence URL<input name="source_url" required type="url" className={input} placeholder="https://…" /></label><label className="text-sm">Review by<input name="review_by_date" required type="date" className={input} /></label><label className="text-sm">Account requirement<input name="account_requirement" className={input} /></label><label className="text-sm sm:col-span-2">Payment requirement<input name="payment_requirement" className={input} /></label></div><div className="flex flex-wrap gap-4 text-sm"><label><input name="membership_required" type="checkbox" /> Membership required</label><label><input name="account_required" type="checkbox" /> Account required</label><label><input name="confirmed" type="checkbox" /> Evidence confirmed</label></div><Message state={state} /><Button disabled={pending}>{pending ? "Saving…" : "Save unpublished programme"}</Button></form>;
}

export function ProgrammeRateForm({ programmeIds }: { programmeIds: string[] }) {
  const [state, action, pending] = useActionState(createProgrammeRate, initialState);
  return <form action={action} className="space-y-3 rounded-lg border p-4"><h2 className="font-semibold">Add product-specific rate</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Programme<select name="programme_id" required className={input}><option value="">Choose…</option>{programmeIds.map((id) => <option key={id}>{id}</option>)}</select></label><label className="text-sm">Stable rate key<input name="rate_key" required className={input} placeholder="apple-10-percent" /></label><label className="text-sm">Gift-card brand<input name="brand_name" required className={input} /></label><label className="text-sm">Mechanic<select name="promotion_type" className={input}><option value="discount">Discount</option><option value="fixed-dollar-discount">Fixed-dollar discount</option><option value="bonus-value">Bonus value</option><option value="fee-waiver">Fee waiver</option></select></label><label className="text-sm">Discount %<input name="discount_percent" type="number" min="0" max="99.99" step="0.01" className={input} /></label><label className="text-sm">Bonus %<input name="bonus_percent" type="number" min="0" step="0.01" className={input} /></label><label className="text-sm">Fixed discount $<input name="fixed_discount_dollars" type="number" min="0" step="0.01" className={input} /></label><label className="text-sm">Fee waiver $<input name="fee_waiver_dollars" type="number" min="0" step="0.01" className={input} /></label><label className="text-sm">Threshold $<input name="threshold_dollars" type="number" min="0" step="0.01" className={input} /></label><label className="text-sm">Membership tier<input name="membership_tier" className={input} /></label><label className="text-sm sm:col-span-2">Product-specific evidence URL<input name="source_url" required type="url" className={input} /></label><label className="text-sm">Review by<input name="review_by_date" required type="date" className={input} /></label><label className="text-sm">Payment requirement<input name="payment_requirement" className={input} /></label></div><label className="text-sm"><input name="confirmed" type="checkbox" /> Evidence confirmed</label><Message state={state} /><Button disabled={pending || programmeIds.length === 0}>{pending ? "Saving…" : "Save unpublished rate"}</Button></form>;
}

export function GiftCardProductForm() {
  const [state, action, pending] = useActionState(createGiftCardProduct, initialState);
  return <form action={action} className="space-y-3 rounded-lg border p-4"><h2 className="font-semibold">Add reviewed product</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Product ID<input name="id" required className={input} placeholder="ultimate-everyone" /></label><label className="text-sm">Public slug<input name="slug" required className={input} /></label><label className="text-sm">Brand<input name="brand" required className={input} /></label><label className="text-sm">Issuer<input name="issuer" className={input} /></label><label className="text-sm">Network<select name="card_network" className={input}><option value="unknown">Unknown</option><option value="visa">Visa</option><option value="mastercard">Mastercard</option><option value="eftpos">eftpos</option><option value="closed-loop">Closed loop</option></select></label><label className="text-sm">Format<select name="format" className={input}><option value="unknown">Unknown</option><option value="digital">Digital</option><option value="physical">Physical</option><option value="digital-and-physical">Digital and physical</option></select></label><label className="text-sm">Variable load<select name="variable_load" className={input}><option value="unknown">Not recorded</option><option value="yes">Yes</option><option value="no">No</option></select></label><label className="text-sm">Mobile wallet<select name="mobile_wallet" className={input}><option value="unknown">Unknown</option><option value="supported">Supported</option><option value="unsupported">Unsupported</option><option value="partial">Partial</option></select></label><label className="text-sm">Minimum denomination<input name="min_denomination" type="number" min="0" step="0.01" className={input} /></label><label className="text-sm">Maximum denomination<input name="max_denomination" type="number" min="0" step="0.01" className={input} /></label><label className="text-sm sm:col-span-2">Evidence URL<input name="source_url" required type="url" className={input} /></label><label className="text-sm sm:col-span-2">Redemption notes<textarea name="redemption_notes" className="min-h-20 w-full rounded-md border bg-background p-3 text-sm" /></label></div><label className="text-sm"><input name="category_restricted" type="checkbox" /> Category restricted</label><Message state={state} /><Button disabled={pending}>{pending ? "Saving…" : "Save inactive product"}</Button></form>;
}

export function GiftCardAcceptanceForm({ products }: { products: Array<{ id: string; brand: string }> }) {
  const [state, action, pending] = useActionState(createGiftCardAcceptance, initialState);
  return <form action={action} className="space-y-3 rounded-lg border p-4"><h2 className="font-semibold">Add acceptance evidence</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Product<select name="product_id" required className={input}><option value="">Choose…</option>{products.map((product) => <option key={product.id} value={product.id}>{product.brand} ({product.id})</option>)}</select></label><label className="text-sm">Merchant name<input name="merchant_name" className={input} /></label><label className="text-sm">Merchant category<input name="merchant_category" className={input} /></label><label className="text-sm">MCC<input name="mcc" type="number" min="1" max="9999" className={input} /></label><label className="text-sm">Evidence status<select name="status" className={input}><option value="verified">Verified by DealStack</option><option value="claimed">Claimed by issuer</option><option value="community">Community reported</option></select></label><label className="text-sm">Outcome<select name="outcome" className={input}><option value="successful">Successful</option><option value="unsuccessful">Known unsuccessful</option></select></label><label className="text-sm">Checked date<input name="checked_at" required type="date" className={input} /></label><label className="text-sm">Evidence URL<input name="source_url" required type="url" className={input} /></label><label className="text-sm sm:col-span-2">Bounded factual notes<textarea name="notes" className="min-h-20 w-full rounded-md border bg-background p-3 text-sm" /></label></div><Message state={state} /><Button disabled={pending || products.length === 0}>{pending ? "Saving…" : "Save private evidence"}</Button></form>;
}

export function ProgrammeEditForm({ programme }: { programme: IntelligenceProgrammeRow }) {
  const [state, action, pending] = useActionState(updateProgramme.bind(null, programme.id), initialState);
  return <form action={action} className="mt-3 grid gap-3 border-t pt-3 sm:grid-cols-2"><label className="text-sm">Provider<input name="provider" required defaultValue={programme.provider} className={input} /></label><label className="text-sm">Name<input name="name" required defaultValue={programme.name} className={input} /></label><label className="text-sm">Kind<select name="programme_kind" defaultValue={programme.programme_kind} className={input}><option value="bank-account">Bank account</option><option value="membership-catalogue">Membership catalogue</option><option value="employee-benefit">Employee benefit</option></select></label><label className="text-sm">Review by<input name="review_by_date" type="date" required defaultValue={programme.review_by_date} className={input} /></label><label className="text-sm sm:col-span-2">Evidence URL<input name="source_url" type="url" required defaultValue={programme.source_url} className={input} /></label><label className="text-sm sm:col-span-2">Terms URL<input name="terms_url" type="url" defaultValue={programme.terms_url ?? ""} className={input} /></label><label className="text-sm">Account requirement<input name="account_requirement" defaultValue={programme.account_requirement ?? ""} className={input} /></label><label className="text-sm">Payment requirement<input name="payment_requirement" defaultValue={programme.payment_requirement ?? ""} className={input} /></label><div className="flex flex-wrap gap-3 text-sm sm:col-span-2"><label><input name="membership_required" type="checkbox" defaultChecked={programme.membership_required} /> Membership required</label><label><input name="account_required" type="checkbox" defaultChecked={programme.account_required} /> Account required</label><label><input name="confirmed" type="checkbox" defaultChecked={programme.confidence === "confirmed"} /> Evidence confirmed</label></div><div className="sm:col-span-2"><Message state={state} /><Button className="mt-2" disabled={pending}>{pending ? "Saving…" : "Update programme"}</Button></div></form>;
}

export function ProgrammeRateEditForm({ rate }: { rate: IntelligenceRateRow }) {
  const [state, action, pending] = useActionState(updateProgrammeRate.bind(null, rate.id), initialState);
  return <form action={action} className="mt-3 grid gap-2 border-t pt-3 sm:grid-cols-2"><label className="text-xs">Brand<input name="brand_name" required defaultValue={rate.brand_name} className={input} /></label><label className="text-xs">Mechanic<select name="promotion_type" defaultValue={rate.promotion_type} className={input}><option value="discount">Discount</option><option value="fixed-dollar-discount">Fixed-dollar discount</option><option value="bonus-value">Bonus value</option><option value="fee-waiver">Fee waiver</option></select></label><label className="text-xs">Discount %<input name="discount_percent" type="number" min="0" step="0.01" defaultValue={rate.discount_percent ?? ""} className={input} /></label><label className="text-xs">Bonus %<input name="bonus_percent" type="number" min="0" step="0.01" defaultValue={rate.bonus_percent ?? ""} className={input} /></label><label className="text-xs">Fixed discount $<input name="fixed_discount_dollars" type="number" min="0" step="0.01" defaultValue={rate.fixed_discount_dollars ?? ""} className={input} /></label><label className="text-xs">Fee waiver $<input name="fee_waiver_dollars" type="number" min="0" step="0.01" defaultValue={rate.fee_waiver_dollars ?? ""} className={input} /></label><label className="text-xs">Threshold $<input name="threshold_dollars" type="number" min="0" step="0.01" defaultValue={rate.threshold_dollars ?? ""} className={input} /></label><label className="text-xs">Tier<input name="membership_tier" defaultValue={rate.membership_tier ?? ""} className={input} /></label><label className="text-xs sm:col-span-2">Payment requirement<input name="payment_requirement" defaultValue={rate.payment_requirement ?? ""} className={input} /></label><label className="text-xs sm:col-span-2">Evidence URL<input name="source_url" type="url" required defaultValue={rate.source_url} className={input} /></label><label className="text-xs">Review by<input name="review_by_date" type="date" required defaultValue={rate.review_by_date} className={input} /></label><label className="self-end text-xs"><input name="confirmed" type="checkbox" defaultChecked={rate.confidence === "confirmed"} /> Evidence confirmed</label><div className="sm:col-span-2"><Message state={state} /><Button size="sm" className="mt-2" disabled={pending}>{pending ? "Saving…" : "Update rate"}</Button></div></form>;
}
